[package]
name = "agent2"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/agent2.rs"
doctest = false

[features]
test-support = [
    "gpui/test-support",
]

[dependencies]
anyhow.workspace = true
chrono.workspace = true
futures.workspace = true
gpui.workspace = true
project.workspace = true
uuid.workspace = true
workspace-hack.workspace = true

[dev-dependencies]
gpui = { workspace = true, "features" = ["test-support"] }
serde_json.workspace = true
util.workspace = true
