[package]
name = "denoise"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
candle-core = { version = "0.9.1", git ="https://github.com/zed-industries/candle", branch = "9.1-patched" }
candle-onnx = { version = "0.9.1", git ="https://github.com/zed-industries/candle", branch = "9.1-patched" }
log.workspace = true

rodio = { workspace = true, features = ["wav_output"] }

rustfft.workspace = true
realfft.workspace = true
thiserror.workspace = true
workspace-hack.workspace = true
