[package]
name = "gpui_site"
version = "0.1.0"
edition = "2021"
description = "Static site generator for the gpui documentation"

[dependencies]
gpui = { path = "../gpui" }
markdown = "0.3"
pulldown-cmark = "0.9"
syntect = "5.2.0"
handlebars = "4.3"
clap = { version = "4.4", features = ["derive"] }
fs_extra = "1.3"
walkdir = "2.4"
toml = "0.8"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
html-escape = "0.2"

[[bin]]
name = "gpui_site"
path = "src/main.rs"
