[package]
name = "scheduler"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/scheduler.rs"

[dependencies]
anyhow = "1.0"
async-task = "4.5"
futures = "0.3"
rand = { version = "0.8", features = ["small_rng"] }
rand_chacha = "0.3"
parking_lot = "0.12"

[features]
test-support = []