[package]
name = "worlds_fair_talk"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[dependencies]
gpui = { workspace = true }
language = { workspace = true }
assistant_tools = { workspace = true }
project = { workspace = true }
fs = { workspace = true }
client = { workspace = true }
call = { workspace = true }
rpc = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
language = { workspace = true, features = ["test-support"] }
project = { workspace = true, features = ["test-support"] }
fs = { workspace = true, features = ["test-support"] }
client = { workspace = true, features = ["test-support"] }
pretty_assertions = { workspace = true }
indoc = { workspace = true }