[package]
name = "assistant_rules"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/assistant_rules.rs"
doctest = false

[dependencies]
anyhow.workspace = true
fs.workspace = true
futures.workspace = true
gpui.workspace = true
util.workspace = true
worktree.workspace = true

[dev-dependencies]
indoc.workspace = true
