[package]
name = "onboarding_ui"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/onboarding_ui.rs"

[features]
test-support = []

[dependencies]
anyhow.workspace = true
welcome.workspace = true
client.workspace = true
command_palette_hooks.workspace = true
component.workspace = true
db.workspace = true
feature_flags.workspace = true
gpui.workspace = true
menu.workspace = true
project.workspace = true
serde_json.workspace = true
settings.workspace = true
settings_ui.workspace = true
theme.workspace = true
ui.workspace = true
util.workspace = true
vim_mode_setting.workspace = true
workspace.workspace = true
zed_actions.workspace = true

[dev-dependencies]
editor = { workspace = true, features = ["test-support"] }
