id = "html"
name = "HTML"
description = "HTML support."
version = "0.1.6"
schema_version = 1
authors = ["Isaac Clayton <slightknack@gmail.com>"]
repository = "https://github.com/zed-industries/zed"

[language_servers.vscode-html-language-server]
name = "vscode-html-language-server"
language = "HTML"

[language_servers.vscode-html-language-server.language_ids]
"HTML" = "html"
"CSS" = "css"

[grammars.html]
repository = "https://github.com/tree-sitter/tree-sitter-html"
commit = "5a5ca8551a179998360b4a4ca2c0f366a35acc03"
