[package]
name = "scripting_tool"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/scripting_tool.rs"
doctest = false

[dependencies]
anyhow.workspace = true
assistant_tool.workspace = true
collections.workspace = true
gpui.workspace = true
language.workspace = true
mlua.workspace = true
parking_lot.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
workspace.workspace = true
regex.workspace = true
rich_text.workspace = true
settings.workspace = true
theme.workspace = true
ui.workspace = true
