[package]
name = "current_commit_sha"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/current_commit_sha.rs"

[dependencies]
