[package]
name = "docs_preprocessor"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[dependencies]
actions.workspace = true
anyhow.workspace = true
clap.workspace = true
mdbook = "0.4.40"
serde.workspace = true
serde_json.workspace = true
settings.workspace = true
regex.workspace = true
rust-embed.workspace = true
util.workspace = true
workspace-hack.workspace = true

[lints]
workspace = true

[[bin]]
name = "docs_preprocessor"
path = "src/main.rs"
