[package]
name = "dap_adapters"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[features]
test-support = [
    "dap/test-support",
    "gpui/test-support",
    "task/test-support",
    "util/test-support",
]
update-schemas = [
    "dep:node_runtime",
    "dep:reqwest_client",
    "dep:settings",
    "dep:tempfile",
]

[lints]
workspace = true

[lib]
path = "src/dap_adapters.rs"
doctest = false

[[bin]]
name = "update-schemas"
path = "src/update_schemas.rs"
required-features = ["update-schemas"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
collections.workspace = true
dap.workspace = true
dotenvy.workspace = true
futures.workspace = true
fs.workspace = true
gpui.workspace = true
json_dotpath.workspace = true
language.workspace = true
log.workspace = true
paths.workspace = true
serde.workspace = true
serde_json.workspace = true
shlex.workspace = true
task.workspace = true
util.workspace = true
workspace-hack.workspace = true

node_runtime = { workspace = true, optional = true }
reqwest_client = { workspace = true, optional = true }
settings = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }

[dev-dependencies]
dap = { workspace = true, features = ["test-support"] }
gpui = { workspace = true, features = ["test-support"] }
task = { workspace = true, features = ["test-support"] }
util = { workspace = true, features = ["test-support"] }
