[package]
name = "shell_parser"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/shell_parser.rs"
doctest = false

[dependencies]
shlex.workspace = true
