name: Run Eval Daily

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  run_eval:
    name: Run Eval
    if: github.repository_owner == 'zed-industries'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxcb-shape0-dev libxcb-xfixes0-dev libxcb1-dev libxcb-render0-dev libxcb-randr0-dev libxcb-xtest0-dev libxcb-keysyms1-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxfixes-dev pkg-config
          ./script/headless && ./script/install-mold 2.34.0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo eval
        run: cargo run -p eval
